### ISSUE TITLE
[Feat] 프로그램 상세 뷰 구현

### ISSUE THREAD

**Issue by timotheekim10** [SOPT-33-iOS-Team-1/SOPKATHON_33-iOS#17]
## 🛠 Issue
- 프로그램 상세 뷰 구현

## 📋 To-do
- [x] 뒤로가기 버튼 커스텀
- [x] 지원하기 버튼 구현
- [x] 스크롤뷰 구현
- [x] 라벨 구현
- [x] 라인 뷰 구현
- [x] 스크롤뷰 수정
- [x] 바인딩 함수 구현
- [x] 뒤로가기 버튼 수정
